In [1]:
import pandas as pd
import numpy as np 
from sklearn.decomposition import NMF

In [16]:
R = pd.read_csv('~/SPICED/movie_recommender/data/UserRating.csv', index_col=0)
R

,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,2.5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
R.fillna(2.5, inplace=True)
R

,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,2.5,4.0,2.5,2.5,4.0,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
2,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
3,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
4,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
5,4.0,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
607,4.0,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
608,2.5,2.0,2.0,2.5,2.5,2.5,2.5,2.5,2.5,4.0,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
609,3.0,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,4.0,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
610,5.0,2.5,2.5,2.5,2.5,5.0,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5

In [14]:
model = NMF(19)

In [18]:
model.fit(R)

NMF(n_components=19)

In [21]:
Q = pd.DataFrame(model.components_, columns=R.columns)
Q

,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
0,0.405387,0.542675,0.681832,0.764072,0.728933,0.520880,0.737757,0.752145,0.782756,0.569596,...,0.770511,0.768965,0.772058,0.772058,0.770511,0.772058,0.770511,0.770511,0.770511,0.766753
1,0.618412,0.330089,0.642636,0.137764,0.495357,0.209283,0.356381,0.278376,0.215802,0.524017,...,0.197879,0.202554,0.193204,0.193204,0.197879,0.193204,0.197879,0.197879,0.197879,0.221954
2,0.669114,0.124471,0.004936,0.079580,0.016482,0.537384,0.000000,0.060499,0.056261,0.260128,...,0.054062,0.056778,0.051346,0.051346,0.054062,0.051346,0.054062,0.054062,0.054062,0.056583
3,3.062355,2.422394,1.124703,0.137202,0.934474,2.160259,1.081565,0.313411,0.164711,2.438906,...,0.030084,0.038453,0.021715,0.021715,0.030084,0.021715,0.030084,0.030084,0.030084,0.032301
4,1.556263,0.642685,0.278055,0.047650,0.190800,0.000000,0.197129,0.016029,0.011059,0.000000,...,0.039202,0.042698,0.035706,0.035706,0.039202,0.035706,0.039202,0.039202,0.039202,0.042301
5,0.720041,0.187602,0.072073,0.128191,0.000000,1.437675,0.000000,0.094284,0.000000,0.046662,...,0.085043,0.088822,0.081264,0.081264,0.085043,0.081264,0.085043,0.085043,0.085043,0.127195
6,0.056623,0.052921,0.117638,0.039245,0.018296,0.049054,0.065086,0.055934,0.034323,0.031360,...,0.039501,0.038885,0.040118,0.040118,0.039501,0.040118,0.039501,0.039501,0.039501,0.038730
7,0.104716,0.426438,0.059514,0.058129,0.099315,0.000000,0.000000,0.076326,0.050670,0.351663,...,0.055757,0.052078,0.059436,0.059436,0.055757,0.059436,0.055757,0.055757,0.055757,0.055609
8,0.195019,0.291559,0.054359,0.031095,0.020838,0.249931,0.038401,0.037718,0.028109,0.217901,...,0.033661,0.033514,0.033808,0.033808,0.033661,0.033808,0.033661,0.033661,0.033661,0.030347
9,0.252525,0.075479,0.025624,0.053292,0.066190,0.415543,0.043260,0.039224,0.066672,0.431997,...,0.039095,0.041329,0.036860,0.036860,0.039095,0.036860,0.039095,0.039095,0.039095,0.039215
10,0.141565,0.000000,0.050272,0.051926,0.052125,0.092610,0.036612,0.048372,0.047520,0.006992,...,0.049672,0.049711,0.049633,0.049633,0.049672,0.049633,0.049672,0.049672,0.049672,0.048842
11,0.023572,0.058706,0.035790,0.031198,0.000000,0.000000,0.062257,0.034042,0.033021,0.020547,...,0.035287,0.035239,0.035335,0.035335,0.035287,0.035335,0.035287,0.035287,0.035287,0.035224
12,0.166741,0.026556,0.057399,0.052510,0.072029,0.075342,0.043615,0.044517,0.053764,0.095670,...,0.050527,0.050561,0.050493,0.050493,0.050527,0.050493,0.050527,0.050527,0.050527,0.051430
13,1.008868,0.587367,0.000000,0.064774,0.000000,0.127344,0.094227,0.101558,0.037235,0.516615,...,0.092464,0.089435,0.095493,0.095493,0.092464,0.095493,0.092464,0.092464,0.092464,0.094342
14,0.000000,0.023300,0.010883,0.052982,0.045539,0.177707,0.052505,0.046505,0.027631,0.115306,...,0.047539,0.047975,0.047103,0.047103,0.047539,0.047103,0.047539,0.047539,0.047539,0.045135
15,0.599186,0.222825,0.312428,0.044614,0.047846,0.475423,0.000553,0.047299,0.025278,0.381764,...,0.046280,0.048292,0.044268,0.044268,0.046280,0.044268,0.046280,0.046280,0.046280,0.044165
16,0.000000,0.046521,0.045061,0.018057,0.011526,0.171159,0.017831,0.027191,0.020535,0.000000,...,0.019816,0.019286,0.020347,0.020347,0.019816,0.020347,0.019816,0.019816,0.019816,0.020075
17,0.086442,0.004004,0.016300,0.041101,0.032052,0.208197,0.040340,0.041059,0.027850,0.001701,...,0.038481,0.038627,0.038336,0.038336,0.038481,0.038336,0.038481,0.038481,0.038481,0.041089
18,0.004665,0.322823,0.003709,0.031077,0.004600,0.220279,0.016051,0.026857,0.001757,0.000000,...,0.026301,0.026462,0.026140,0.026140,0.026301,0.026140,0.026301,0.026301,0.026301,0.023831

In [22]:
P = pd.DataFrame(model.transform(R), index=R.index)
P

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
userId,,,,,,,,,,,,,,,,,,,
1,2.769019,0.458045,0.121795,0.048479,0.253427,0.069915,0.905618,0.134395,0.835219,0.114666,0.147498,0.000000,1.924979,0.137449,0.068693,1.344166,0.000000,0.000000,0.239748
2,3.020375,0.194692,0.135440,0.055874,0.200612,0.197018,0.314961,0.485829,0.187734,0.221988,0.123440,0.118893,0.199777,0.141477,0.045708,0.154035,0.145052,0.134496,0.073326
3,3.032919,0.176499,0.137254,0.056147,0.190917,0.083263,0.240061,0.251905,0.491716,0.374686,0.180301,0.000000,0.085594,0.138227,0.087982,0.191251,0.123896,0.294061,0.106343
4,2.863748,0.310189,0.602184,0.038652,0.474899,0.000000,0.365716,0.349367,0.116553,0.077220,1.525693,0.595320,0.127190,0.173798,0.054937,0.271866,0.147164,0.046451,0.068486
5,3.018408,0.201735,0.196154,0.223440,0.289743,0.151216,0.426909,0.127739,0.301248,0.110883,0.202612,0.151045,0.197970,0.134788,0.161979,0.058379,0.056589,0.082702,0.059205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.310560,0.000000,0.106354,0.000000,0.640050,0.000000,0.000000,0.644727,0.000000,0.000000,0.510914,5.372963,1.168291,0.346131,7.398924,0.000000,0.855001,0.000000,0.000000
607,3.021155,0.000000,0.160150,0.175209,0.342050,0.246909,0.408048,0.112521,0.528641,0.365650,0.245243,0.232133,0.000000,0.000000,0.000000,0.786535,0.000000,0.298908,0.074245
608,2.628684,0.501710,0.024446,0.000000,0.000000,0.249737,0.699047,0.000000,1.591301,3.523518,0.126134,0.025175,0.000000,0.000000,1.575655,0.000000,0.033957,0.644215,0.000000
609,3.042372,0.212052,0.169544,0.167876,0.198340,0.138958,0.276134,0.208064,0.301175,0.246179,0.058922,0.079780,0.059669,0.128259,0.153382,0.127608,0.083165,0.077408,0.084019
610,1.948091,0.000000,0.018584,0.000000,0.884763,0.000000,0.031953,0.599916,0.000000,1.080388,0.462828,1.277391,3.347751,0.613006,0.007326,0.000000,0.000000,15.882468,0.000000

In [23]:
# HERE I WILL TRY THE PICKLE THING LATER

In [24]:
flask_user_input = {
    '126': '5',
    '7002': '3',
    '600': '4'
}

In [25]:
new_user_vector = pd.DataFrame([np.nan]*len(R.columns), index=R.columns).transpose()
new_user_vector

,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN